### ISSUE TITLE
Implement "saving grace"

### ISSUE THREAD

**Issue by ktk** [zazuko/varnish-post#1]
With this approach we can deliver content even if the original TTL is older: https://info.varnish-software.com/blog/systematic-content-validation-with-varnish

**Comment by ludovicm67** [comment]
This supposes that the backend is sending ETag headers, which is not the case for Stardog and Fuseki for now.

**Comment by ktk** [comment]
Issue for Fuseki https://issues.apache.org/jira/browse/JENA-388

**Comment by ludovicm67** [comment]
Fuseki classified the issue as "Won't Do".
Since we don't have any need for now, I'm closing this issue.
